import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { writeFile } from 'node:fs/promises';

const execFileAsync = promisify(execFile);

export const RESOLVER_IP = '172.30.0.1';
export const BUILD_NETWORK = 'build-restricted';
export const IPSET_NAME = 'build-allowed-ips';

export const ALLOWLISTED_FQDNS = [
  'pub.dev',
  'storage.googleapis.com',
  'registry.npmjs.org',
  'registry.yarnpkg.com',
  'repo1.maven.org',
  'central.maven.org',
  'plugins.gradle.org',
  'dl.google.com',
  'services.gradle.org',
  'jcenter.bintray.com',
  'github.com',
  'objects.githubusercontent.com',
  'raw.githubusercontent.com',
];

export function generateDnsmasqConfig(): string {
  const lines: string[] = [
    '# peep cloud build — FQDN allowlist',
    '# Auto-generated by network-setup.ts — do not edit manually',
    '',
    `# Listen only on the build bridge interface`,
    `listen-address=${RESOLVER_IP}`,
    `bind-interfaces`,
    '',
    '# Explicit upstream resolvers (bypassing host /etc/resolv.conf).',
    '# Architectural decision: DNS queries for allowlisted domains leave',
    '# this host to Google/Cloudflare public resolvers. Acceptable for MVP',
    '# since only pre-approved package-registry domains are ever queried.',
    'no-resolv',
    'server=8.8.8.8',
    'server=1.1.1.1',
    '',
    '# For each allowlisted FQDN: resolve normally AND add IPs to ipset',
  ];
  for (const fqdn of ALLOWLISTED_FQDNS) {
    lines.push(`ipset=/${fqdn}/${IPSET_NAME}`);
  }
  lines.push(
    '',
    '# CATCH-ALL: return NXDOMAIN for any FQDN not matched above.',
    'address=/#/',
  );
  return lines.join('\n') + '\n';
}

export async function writeDnsmasqConfig(
  path = '/etc/dnsmasq.d/build-allowlist.conf',
): Promise<void> {
  await writeFile(path, generateDnsmasqConfig(), 'utf-8');
  console.log(`[network-setup] dnsmasq config written to ${path}`);
}

export async function setupBuildNetwork(): Promise<void> {
  try {
    await execFileAsync('docker', [
      'network', 'create',
      '--driver', 'bridge',
      '--subnet', '172.30.0.0/24',
      '--gateway', RESOLVER_IP,
      '--opt', `com.docker.network.bridge.name=build0`,
      BUILD_NETWORK,
    ]);
    console.log(`[network-setup] Created Docker network: ${BUILD_NETWORK}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists')) {
      console.log(`[network-setup] Network ${BUILD_NETWORK} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  try {
    await execFileAsync('ipset', [
      'create', IPSET_NAME, 'hash:ip', 'timeout', '3600',
    ]);
    console.log(`[network-setup] Created ipset: ${IPSET_NAME}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists') || err.stderr?.includes('set with the same name')) {
      console.log(`[network-setup] ipset ${IPSET_NAME} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  const rules: [string, string[]][] = [
    ['FORWARD', ['-o', 'build0', '-m', 'state', '--state', 'ESTABLISHED,RELATED', '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '443',
      '-m', 'set', '--match-set', IPSET_NAME, 'dst', '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-j', 'DROP']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-j', 'DROP']],
    ['FORWARD', ['-i', 'build0', '-j', 'DROP']],
  ];

  for (const [chain, ruleArgs] of rules.reverse()) {
    try {
      await execFileAsync('iptables', ['-C', chain, ...ruleArgs]);
    } catch {
      await execFileAsync('iptables', ['-I', chain, ...ruleArgs]);
    }
  }

  console.log('[network-setup] iptables rules applied to build0 interface');
}

export function getDnsmasqConfigForAudit(): string {
  return generateDnsmasqConfig();
}
