// packages/cloud-build/src/network-setup.ts
// One-time host network setup for the build sandbox.
// Must be run as root on the Docker host before starting any worker.
//
// FQDN-based allowlist architecture (required for MVP):
//   dnsmasq: resolves only allowlisted FQDNs → populates ipset "build-allowed-ips"
//   ipset:   tracks IPs that dnsmasq has legitimately resolved
//   iptables: ACCEPT HTTPS only to IPs in the ipset; DROP everything else
//
// WHY NOT CIDR-BASED FILTERING:
//   Cloudflare's 104.16.0.0/13 hosts thousands of unrelated domains alongside
//   npmjs.org. An attacker's Cloudflare Worker at attacker.workers.dev would
//   pass IP-range filtering. FQDN-based matching is the required approach.
//
// FAIL-CLOSED DESIGN (dnsmasq crash):
//   Containers are started with --dns=172.30.0.1 and NO fallback resolver.
//   If dnsmasq crashes or becomes unreachable:
//     - DNS queries inside containers return connection refused or timeout
//     - npm install and flutter pub get fail immediately with DNS errors
//     - The build exits non-zero; the job is marked 'failed'
//     - NO connection to any external server is possible
//   This is a deliberate fail-closed security decision. A dnsmasq outage causes
//   build failures (operational inconvenience) rather than allowing unconstrained
//   network access (security failure). The operational cost is acceptable.

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { writeFile } from 'node:fs/promises';

const execFileAsync = promisify(execFile);

/** IP of the Docker host on the build-restricted bridge — dnsmasq listens here */
export const RESOLVER_IP = '172.30.0.1';

/** Name of the restricted Docker network */
export const BUILD_NETWORK = 'build-restricted';

/** Name of the ipset tracking legitimately-resolved IPs */
export const IPSET_NAME = 'build-allowed-ips';

/**
 * Allowlisted FQDNs.
 * dnsmasq resolves these normally and adds resolved IPs to the ipset.
 * All other FQDNs return NXDOMAIN.
 *
 * Security note: these entries are FQDNs, not wildcard patterns.
 * Subdomains (e.g., cdn.registry.npmjs.org) must be listed explicitly if needed.
 */
export const ALLOWLISTED_FQDNS = [
  'pub.dev',
  'storage.googleapis.com',
  'registry.npmjs.org',
  'registry.yarnpkg.com',
  'repo1.maven.org',
  'central.maven.org',
  'plugins.gradle.org',
  'dl.google.com',
  'services.gradle.org',
  'jcenter.bintray.com',
  'github.com',
  'objects.githubusercontent.com',
  'raw.githubusercontent.com',
];

/**
 * Generates the dnsmasq configuration for the build allowlist.
 * This file should be written to /etc/dnsmasq.d/build-allowlist.conf on the host.
 *
 * Key properties:
 *   - Listens only on the bridge interface IP (172.30.0.1)
 *   - ipset= directives add resolved IPs to the ipset on each lookup
 *   - address=/#/ returns NXDOMAIN for ALL other queries (not just non-allowlisted)
 *     This is the catch-all block: any FQDN not in the allowlist → NXDOMAIN
 */
export function generateDnsmasqConfig(): string {
  const lines: string[] = [
    '# peep cloud build — FQDN allowlist',
    '# Auto-generated by network-setup.ts — do not edit manually',
    '',
    `# Listen only on the build bridge interface`,
    `listen-address=${RESOLVER_IP}`,
    `bind-interfaces`,
    '',
    '# Explicit upstream resolvers (bypassing host /etc/resolv.conf)',
    'no-resolv',
    'server=8.8.8.8',
    'server=1.1.1.1',
    '',
    '# For each allowlisted FQDN: resolve normally AND add IPs to ipset',
  ];

  for (const fqdn of ALLOWLISTED_FQDNS) {
    lines.push(`ipset=/${fqdn}/${IPSET_NAME}`);
  }

  lines.push(
    '',
    '# CATCH-ALL: return NXDOMAIN for any FQDN not matched above.',
    '# address=/#/ makes dnsmasq return NXDOMAIN for every non-allowlisted query.',
    '# This is the enforcing rule — dnsmasq does NOT forward unknown queries upstream.',
    'address=/#/',
  );

  return lines.join('\n') + '\n';
}

/**
 * Writes the dnsmasq configuration file.
 * Path: /etc/dnsmasq.d/build-allowlist.conf (requires root)
 */
export async function writeDnsmasqConfig(
  path = '/etc/dnsmasq.d/build-allowlist.conf',
): Promise<void> {
  await writeFile(path, generateDnsmasqConfig(), 'utf-8');
  console.log(`[network-setup] dnsmasq config written to ${path}`);
}

/**
 * Creates the restricted Docker bridge network and configures iptables.
 * Idempotent — safe to call on worker restart.
 *
 * iptables rules applied:
 *   ACCEPT DNS  → only to 172.30.0.1:53 (our dnsmasq, NOT public resolvers)
 *   ACCEPT HTTPS → only to IPs in the build-allowed-ips ipset
 *   BLOCK DNS   → any DNS to other destinations (prevent bypass via 8.8.8.8)
 *   DROP all    → everything else
 *
 * Fail-closed: if dnsmasq is unreachable, DNS queries fail → builds fail safely.
 */
export async function setupBuildNetwork(): Promise<void> {
  // 1. Create the restricted Docker network (idempotent)
  try {
    await execFileAsync('docker', [
      'network', 'create',
      '--driver', 'bridge',
      '--opt', `com.docker.network.bridge.name=build0`,
      BUILD_NETWORK,
    ]);
    console.log(`[network-setup] Created Docker network: ${BUILD_NETWORK}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists')) {
      console.log(`[network-setup] Network ${BUILD_NETWORK} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  // 2. Create the ipset (idempotent; IPs expire after 1 hour to handle CDN rotation)
  try {
    await execFileAsync('ipset', [
      'create', IPSET_NAME, 'hash:ip', 'timeout', '3600',
    ]);
    console.log(`[network-setup] Created ipset: ${IPSET_NAME}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists') || err.stderr?.includes('set with the same name')) {
      console.log(`[network-setup] ipset ${IPSET_NAME} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  // 3. Apply iptables rules to the build0 bridge interface
  //    Using -I (insert at top) to take precedence over any existing rules.
  //    Order matters: ACCEPT rules must come before the DROP catch-all.

  const rules: [string, string[]][] = [
    // ACCEPT return traffic for established connections (must be checked first)
    ['FORWARD', ['-o', 'build0', '-m', 'state', '--state', 'ESTABLISHED,RELATED', '-j', 'ACCEPT']],

    // ACCEPT DNS only to our custom resolver (fail-closed: no other DNS allowed)
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],

    // ACCEPT HTTPS only to IPs that dnsmasq has legitimately resolved
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '443',
      '-m', 'set', '--match-set', IPSET_NAME, 'dst', '-j', 'ACCEPT']],

    // BLOCK DNS to any other destination (prevent hardcoded 8.8.8.8 or similar)
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-j', 'DROP']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-j', 'DROP']],

    // DROP everything else (HTTP, FTP, SMTP, arbitrary TCP/UDP, etc.)
    ['FORWARD', ['-i', 'build0', '-j', 'DROP']],
  ];

  // Reverse the rules before inserting so that the first rule ends up at the top
  // (since -I pushes subsequent rules down)
  for (const [chain, ruleArgs] of rules.reverse()) {
    // Check if rule already exists before inserting
    try {
      await execFileAsync('iptables', ['-C', chain, ...ruleArgs]);
      // Rule exists — skip
    } catch {
      // Rule does not exist — insert it
      await execFileAsync('iptables', ['-I', chain, ...ruleArgs]);
    }
  }

  console.log('[network-setup] iptables rules applied to build0 interface');
}

/**
 * Returns the dnsmasq configuration as a string for inspection/testing.
 * This is the same content that would be written to disk.
 */
export function getDnsmasqConfigForAudit(): string {
  return generateDnsmasqConfig();
}
