import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { writeFile, readFile } from 'node:fs/promises';

const execFileAsync = promisify(execFile);

export const RESOLVER_IP = '172.30.0.1';
export const BUILD_NETWORK = 'build-restricted';
export const IPSET_NAME = 'build-allowed-ips';

export const ALLOWLISTED_FQDNS = [
  'pub.dev',
  'storage.googleapis.com',
  'registry.npmjs.org',
  'registry.yarnpkg.com',
  'repo1.maven.org',
  'central.maven.org',
  'plugins.gradle.org',
  'dl.google.com',
  'services.gradle.org',
  'jcenter.bintray.com',
  // Note: github.com and release-assets.githubusercontent.com host arbitrary user content.
  // This is an accepted MVP risk. Plan: pre-baked Gradle in the image or a filtering proxy.
  // Additionally, the API server currently runs as root in PM2 (needed here for iptables/dnsmasq);
  // splitting the build worker from the API process is a pre-launch item.
  'github.com',
  'objects.githubusercontent.com',
  'raw.githubusercontent.com',
  'release-assets.githubusercontent.com',
  'plugins-artifacts.gradle.org',
];

export function generateDnsmasqConfig(): string {
  const lines: string[] = [
    '# peep cloud build — FQDN allowlist',
    '# Auto-generated by network-setup.ts — do not edit manually',
    '',
    `# Listen only on the build bridge interface`,
    `listen-address=${RESOLVER_IP}`,
    `bind-interfaces`,
    '',
    '# Explicit upstream resolvers (bypassing host /etc/resolv.conf).',
    '# Architectural decision: DNS queries for allowlisted domains leave',
    '# this host to Google/Cloudflare public resolvers. Acceptable for MVP',
    '# since only pre-approved package-registry domains are ever queried.',
    'no-resolv',
    'server=8.8.8.8',
    'server=1.1.1.1',
    '',
    '# For each allowlisted FQDN: resolve normally AND add IPs to ipset',
  ];
  for (const fqdn of ALLOWLISTED_FQDNS) {
    lines.push(`ipset=/${fqdn}/${IPSET_NAME}`);
  }
  lines.push(
    '',
    '# CATCH-ALL: return NXDOMAIN for any FQDN not matched above.',
    'address=/#/',
  );
  return lines.join('\n') + '\n';
}

export async function writeDnsmasqConfig(
  path = '/etc/dnsmasq.d/build-allowlist.conf',
): Promise<void> {
  const newConfig = generateDnsmasqConfig();
  let oldConfig = '';
  try {
    oldConfig = await readFile(path, 'utf-8');
  } catch (err) {
    // Ignore read error (file might not exist)
  }

  if (oldConfig !== newConfig) {
    await writeFile(path, newConfig, 'utf-8');
    console.log(`[network-setup] dnsmasq config written to ${path}`);
    try {
      await execFileAsync('systemctl', ['restart', 'dnsmasq']);
      console.log(`[network-setup] dnsmasq restarted`);
    } catch (err: any) {
      console.error(`[network-setup] ERROR: Failed to restart dnsmasq. The running dnsmasq still has the OLD allowlist: ${err.message}`);
    }
  } else {
    console.log(`[network-setup] dnsmasq config is up to date`);
  }
}

export async function setupBuildNetwork(): Promise<void> {
  try {
    const { stdout } = await execFileAsync('docker', ['network', 'inspect', BUILD_NETWORK]);
    const networkInfo = JSON.parse(stdout)[0];
    const options = networkInfo.Options || {};
    if (options['com.docker.network.bridge.enable_icc'] !== 'false') {
      const containers = networkInfo.Containers || {};
      if (Object.keys(containers).length === 0) {
        console.log(`[network-setup] Recreating network ${BUILD_NETWORK} to add enable_icc=false`);
        await execFileAsync('docker', ['network', 'rm', BUILD_NETWORK]);
      } else {
        console.log('[network-setup] WARNING: enable_icc not enforced (containers attached); relying on iptables only');
      }
    }
  } catch (err) {
    // Ignore error if network doesn't exist
  }

  try {
    await execFileAsync('docker', [
'network', 'create',
      '--driver', 'bridge',
      '--subnet', '172.30.0.0/24',
      '--gateway', RESOLVER_IP,
      '--opt', `com.docker.network.bridge.name=build0`,
      '--opt', `com.docker.network.bridge.enable_icc=false`,
      BUILD_NETWORK,
    ]);
    console.log(`[network-setup] Created Docker network: ${BUILD_NETWORK}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists')) {
      console.log(`[network-setup] Network ${BUILD_NETWORK} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  try {
    await execFileAsync('ipset', [
      'create', IPSET_NAME, 'hash:ip', 'timeout', '3600',
    ]);
    console.log(`[network-setup] Created ipset: ${IPSET_NAME}`);
  } catch (err: any) {
    if (err.stderr?.includes('already exists') || err.stderr?.includes('set with the same name')) {
      console.log(`[network-setup] ipset ${IPSET_NAME} already exists — skipping create`);
    } else {
      throw err;
    }
  }

  const oldRules: [string, string[]][] = [
    ['FORWARD', ['-o', 'build0', '-m', 'state', '--state', 'ESTABLISHED,RELATED', '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '443', '-m', 'set', '--match-set', IPSET_NAME, 'dst', '-j', 'ACCEPT']],
    ['FORWARD', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-j', 'DROP']],
    ['FORWARD', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-j', 'DROP']],
    ['FORWARD', ['-i', 'build0', '-j', 'DROP']],
  ];

  for (const [chain, ruleArgs] of oldRules) {
    let exists = true;
    while (exists) {
      try {
        await execFileAsync('iptables', ['-C', chain, ...ruleArgs]);
        await execFileAsync('iptables', ['-D', chain, ...ruleArgs]);
      } catch {
        exists = false;
      }
    }
  }

  const rules: [string, string[]][] = [
    ['DOCKER-USER', ['-o', 'build0', '-m', 'conntrack', '--ctstate', 'RELATED,ESTABLISHED', '-j', 'ACCEPT']],
    ['DOCKER-USER', ['-i', 'build0', '-o', 'build0', '-j', 'DROP']],
    ['DOCKER-USER', ['-i', 'build0', '-p', 'udp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['DOCKER-USER', ['-i', 'build0', '-p', 'tcp', '--dport', '53', '-d', RESOLVER_IP, '-j', 'ACCEPT']],
    ['DOCKER-USER', ['-i', 'build0', '-p', 'tcp', '--dport', '443', '-m', 'set', '--match-set', IPSET_NAME, 'dst', '-j', 'ACCEPT']],
    ['DOCKER-USER', ['-i', 'build0', '-j', 'DROP']],
  ];

  for (const [chain, ruleArgs] of rules.reverse()) {
    try {
      await execFileAsync('iptables', ['-C', chain, ...ruleArgs]);
    } catch {
      await execFileAsync('iptables', ['-I', chain, ...ruleArgs]);
    }
  }

  console.log('[network-setup] iptables rules applied to build0 interface');

  const { stdout: iptablesOut } = await execFileAsync('iptables', ['-S', 'DOCKER-USER']);
  const build0Rules = iptablesOut.trim().split('\n').filter(l => l.includes(' build0'));
  const lastRule = build0Rules[build0Rules.length - 1];
  if (!lastRule || !lastRule.includes('-i build0 -j DROP')) {
    throw new Error('Verification failed: catch-all DROP is not the last build0 rule in DOCKER-USER chain: ' + lastRule);
  }

  await writeDnsmasqConfig();
}

export function getDnsmasqConfigForAudit(): string {
  return generateDnsmasqConfig();
}
